---
title: "MSOpt class"
output: html_notebook
---

### Test score: MSOpt e Score

```{r}
library(multiDoE)
options(digits = 10)

facts <- list(1:2, 3:4)
units <- list(12, 4)
levels <- list(4, 4, 4, 2)
etas <- list(1, 1)
criteria <- c('I', 'Id', 'D', 'A', 'Ds', 'As')
model <- "quadratic"    

example <- matrix(c(  1, -1,  1,  0,
                      1, -1, -1,  1,
                      1, -1, -1,  1,
                      1, -1, -1,  1,
                      1, -1,  1,  0,
                      1, -1, -1,  1,
                      1, -1, -1,  1,
                      1, -1, -1,  1,
                      1,  1,  1,  1,
                      1,  1,  0,  1,
                      1,  1, -1,  0,
                      1,  1,  1, -1,
                      1,  1,  1,  1,
                      1,  1,  0,  1,
                      1,  1, -1,  0,
                      1,  1,  1, -1,
                     -1, -1,  0,  1,
                     -1, -1,  1, -1,
                     -1, -1,  1, -1,
                     -1, -1,  0,  1,
                      0, -1,  0, -1,
                      0, -1,  1,  1,
                      0, -1, -1, -1,
                      0, -1, -1,  0,
                      1,  1,  0,  1,
                      1,  1,  1, -1,
                      1,  1,  1,  1,
                      1,  1, -1,  0,
                     -1,  1, -1,  1,
                     -1,  1, -1, -1,
                     -1,  1,  1, -1,
                     -1,  1,  1,  1,
                      0, -1,  0, -1,
                      0, -1,  1,  1,
                      0, -1, -1,  0,
                      0, -1, -1, -1,
                      0, -1,  0, -1,
                      0, -1,  1,  1,
                      0, -1, -1, -1,
                      0, -1, -1,  0,
                      0,  0,  1,  0,
                      0,  0,  1,  0,
                      0,  0,  1,  0,
                      0,  0,  1,  0,
                     -1,  1,  1, -1,
                     -1,  1,  1,  1,
                     -1,  1, -1, -1,
                     -1,  1, -1,  1),
                  ncol = 4, byrow = T)

msopt <- MSOpt(facts, units, levels, etas, criteria, model)
score <- Score(msopt, example)
```

### Expected result 

```{r}
print(c(1.205934492800000, 0.734833087100000, 0.108876783400000, 0.406282668000000, 0.109221258400000,   0.168837086100000))
print(score)
```


