---
title: "instance_2 (2013)"
output: html_document
---

### MSOpt  

```{r}
library(multiDoE)
options(digits = 15)

facts <- list(1, 2:5)
units <- list(21, 2)
levels <- 3
etas <- list(1)
criteria <- c('I', 'Id', 'D', 'A', 'Ds', 'As')
model <- "interaction"

msopt <- MSOpt(facts, units, levels, etas, criteria, model)
msopt
```

### Score  

```{r}

example <- matrix(c( 1,  1,  1,  0,  0,
                     1, -1, -1,  1, -1,
                     1,  0, -1,  0,  0,
                     1,  1,  1, -1,  1,
                     1, -1,  1,  1, -1,
                     1, -1, -1, -1,  1,
                     0,  1, -1,  0,  0,
                     0,  1,  1,  1, -1,
                     0, -1, -1,  0,  0,
                     0,  0,  0,  1,  1,
                     0,  0,  1, -1,  0,
                     0, -1,  0,  0,  1,
                     0,  0,  1,  0,  1,
                     0, -1,  0, -1,  0,
                     0,  1, -1, -1,  1,
                     0,  0,  0,  0,  0,
                    -1,  0,  0,  1,  0,
                    -1,  1,  1, -1, -1,
                     1, -1,  1,  1,  1,
                     1,  1, -1,  1, -1,
                     0,  0,  0,  0,  0,
                     0, -1,  1, -1,  1,
                    -1, -1,  1, -1,  1,
                    -1,  1, -1,  1, -1,
                     0,  1, -1, -1, -1,
                     0,  0,  0,  0,  0,
                    -1,  0,  0,  0, -1,
                    -1,  1,  1,  1,  1,
                     0, -1, -1,  1,  0,
                     0,  0,  0,  0, -1,
                    -1, -1,  1,  1, -1,
                    -1,  0, -1, -1,  1,
                     0,  0, -1, -1, -1,
                     0,  1,  0,  0,  1,
                    -1, -1, -1,  1,  1,
                    -1,  1,  0, -1,  0,
                     1, -1,  1, -1, -1,
                     1,  0,  0,  1,  0,
                     1,  1,  0, -1, -1,
                     1,  1, -1,  1,  1,
                    -1,  0,  1,  0,  0,
                    -1, -1, -1, -1, -1),
                  ncol = 5, byrow = T)

score <- Score(msopt, example)

print(c(0.395194502700000, 0.333949061700000, 0.083963412300000, 0.112928750900000, 0.084644937000000, 0.081678751000000))
print(score)
```


### MSSearch (Single-criteria)
```{r}
library(multiDoE)
set.seed(13)
options(digits = 15)

facts <- list(1, 2:5)
units <- list(21, 2)
levels <- 3
etas <- list(1)
criteria <- c('Id')
model <- "quadratic"

msopt1 <- MSOpt(facts, units, levels, etas, criteria, model)
mssearch1 <- MSSearch(msopt1, 1, "Restarts", 100, "Start", example)
mssearch1
# file_name <- here::here("tests/testthat/test_data/mss1_i3.Rds")
# saveRDS(mssearch1, file = file_name)
```

### TPLSearch  

```{r}
library(multiDoE)
set.seed(345)
options(digits = 10)

facts <- list(1, 2:5)
units <- list(21, 2)
levels <- 3
etas <- list(1)
# criteria <-  c('I', 'Id', 'D', 'A', 'Ds', 'As')
criteria <-  c('A', 'Ds', 'As')
model <- "main"

lCrit <- length(criteria)
iters <- 5 * lCrit
restarts <- 100
restInit <- 2
i = 70

tpls <- runTPLS(facts,units, criteria, model, iters, "Restarts", restarts)

```
