---
title: "esperimento4_p2"
output: html_document
---

### Test score: MSOpt e Score

```{r}
options(digits = 10)
library(multiDoE)

facts <- list(c(), 1:3)
units <- list(7, 4)
levels <- 3
etas <- list(1)
criteria <- c('I', 'Id', 'D', 'A', 'Ds', 'As')
model <- 'quadratic'

example <- matrix(c( 0,  0,  0,
                     1, -1, -1,
                    -1,  1, -1,
                    -1, -1,  1,
                     1, -1,  1,
                     0,  1,  0,
                    -1, -1, -1,
                     0,  0,  0,
                     0,  0,  0,
                     1,  0,  1,
                     0, -1, -1,
                    -1,  1,  0,
                     1,  1,  0,
                     0, -1,  1,
                    -1,  1,  1,
                    -1,  0, -1,
                     0, -1,  0,
                     0,  0,  1,
                     1,  1, -1,
                    -1,  0,  0,
                    -1, -1,  0,
                     0,  1,  1,
                     1,  0, -1,
                     0,  0,  0,
                     1,  1,  1,
                     0,  1, -1,
                    -1,  0,  1,
                     1, -1,  0),
                   ncol = 3, byrow = T)

msopt <- MSOpt(facts, units, levels, etas, criteria, model)
score <- Score(msopt, example)
```

### Expected result 

```{r}
print(c(0.346163804300000, 0.177527693800000, 0.103064944200000, 0.128787948000000, 0.096959114100000, 0.086644705600000))
print(score)
```


### MSSearch (Single-criteria)

```{r}
library(multiDoE)
set.seed(13)
options(digits = 10)

facts <- list(c(), 1:3)
units <- list(7, 4)
levels <- 3
etas <- list(1)
criteria <- c('I', 'Id', 'D', 'A', 'Ds', 'As')
model <- "quadratic"

msopt1 <- MSOpt(facts, units, levels, etas, criteria, model)
mssearch1 <- MSSearch(msopt1, rep(1/6, 6), "Restarts", 100, "Start", example,
                      "Normalize", c(rep(0.2,6), rep(0.5,6)))
mssearch1
# file_name <- here::here("tests/testthat/test_data/mssM_i6.Rds")
# saveRDS(mssearch1, file = file_name)
```

### TPLSearch  

```{r}
library(multiDoE)
set.seed(345)
options(digits = 10)

facts <- list(c(), 1:3)
units <- list(7, 4)
levels <- 3
etas <- list(1)
criteria <- c('I', 'Id')
model <- 'main'

lCrit <- length(criteria)
iters <- 10 * lCrit
restarts <- 100
restInit <- 2
i = 70

tpls <- runTPLS(facts,units, criteria, model, iters, "Etas", etas,
        "Levels", levels, "Restarts", restarts, "RestInit",
        restInit, "RngSeed", i)

```




