---
title: "instance_3"
output: html_document
---

### MSOpt e Score 

```{r}
library(multiDoE)
options(digits = 10)

facts <- list(1:3, 4:6)
units <- list(12, 4)
levels <- 3
etas <- list(1)
criteria <- c('I', 'Id', 'D', 'A', 'Ds', 'As')
model <- 'quadratic'

example <- matrix(c( 0,  1,  1, -1,  0,  0,
                     0,  1,  1,  0,  0,  1,
                     0,  1,  1,  0,  1, -1,
                     0,  1,  1,  1, -1,  0,
                     0, -1,  0,  0, -1,  0,
                     0, -1,  0,  0,  0,  0,
                     0, -1,  0,  1,  1,  1,
                     0, -1,  0, -1,  0, -1,
                     1, -1, -1,  1, -1,  1,
                     1, -1, -1,  1,  1, -1,
                     1, -1, -1, -1, -1, -1,
                     1, -1, -1, -1,  1,  1,
                    -1,  1, -1, -1,  1,  1,
                    -1,  1, -1,  1, -1,  1,
                    -1,  1, -1, -1, -1, -1,
                    -1,  1, -1,  1,  1, -1,
                     1,  0,  1,  0,  1,  0,
                     1,  0,  1, -1, -1,  1,
                     1,  0,  1,  0, -1, -1,
                     1,  0,  1,  1,  0,  0,
                     0,  0, -1,  0,  0,  0,
                     0,  0, -1,  1,  1,  0,
                     0,  0, -1, -1, -1,  1,
                     0,  0, -1,  0,  0, -1,
                    -1, -1, -1,  1,  1,  1,
                    -1, -1, -1,  1, -1, -1,
                    -1, -1, -1, -1,  1, -1,
                    -1, -1, -1, -1, -1,  1,
                     1,  1,  0,  1,  0, -1,
                     1,  1,  0,  1,  1,  1,
                     1,  1,  0,  0, -1,  0,
                     1,  1,  0, -1,  1, -1,
                     0,  0,  0,  1, -1, -1,
                     0,  0,  0,  0,  0,  1,
                     0,  0,  0, -1,  0,  0,
                     0,  0,  0,  0,  0,  0,
                    -1,  0,  0, -1,  1, -1,
                    -1,  0,  0,  0,  0,  0,
                    -1,  0,  0,  1,  0,  0,
                    -1,  0,  0,  0, -1,  0,
                    -1, -1,  1,  1,  1, -1,
                    -1, -1,  1,  1, -1,  1,
                    -1, -1,  1, -1,  1,  1,
                    -1, -1,  1, -1, -1, -1,
                    -1,  1,  1,  1,  1,  1,
                    -1,  1,  1,  0,  0, -1,
                    -1,  1,  1, -1,  1,  0,
                    -1,  1,  1, -1, -1,  1),
                 ncol = 6, byrow = T)

msopt <- MSOpt(facts, units, levels, etas, criteria, model)
score <- Score(msopt, example)

# expected output 
print(c(0.822843249300000, 0.719189332100000, 0.087740799100000, 0.176822808600000, 0.087184909200000, 0.119542430200000))
print(score)

```

### MSSearch (Single-criteria)

```{r}
library(multiDoE)
set.seed(13)
options(digits = 10)

facts <- list(1:3, 4:6)
units <- list(12, 4)
levels <- 3
etas <- list(1)
criteria <- c('D')
model <- "quadratic"

msopt1 <- MSOpt(facts, units, levels, etas, criteria, model)
mssearch1 <- MSSearch(msopt1, 1, "Restarts", 50, "Start", example)
mssearch1
```



### MSSearch (Multi-criteria) 

```{r}
library(multiDoE)
set.seed(123)
options(digits = 10)

facts <- list(1:3, 4:6)
units <- list(12, 4)
levels <- 3
etas <- list(1)
criteria <- c('I', 'Id', 'D', 'A', 'Ds', 'As')
model <- "quadratic"

msopt <- MSOpt(facts, units, levels, etas, criteria, model)
mssearchM <- MSSearch(msopt, rep(1/6, 6) , "Restarts", 100)
mssearchM
```


### TPLSearch  

```{r}
library(multiDoE)
set.seed(345)
options(digits = 10)

facts <- list(1:3, 4:6)
units <- list(12, 4)
levels <- 3
etas <- list(1)
# criteria <-  c('I', 'Id', 'D', 'A', 'Ds', 'As')
criteria <-  c('A', 'Ds')
model <- "quadratic"

lCrit <- length(criteria)
iters <- 10 * lCrit
restarts <- 100
restInit <- 2
i = 70

tpls <- runTPLS(facts,units, criteria, model, iters, "Etas", etas,
        "Levels", levels, "Restarts", restarts, "RestInit",
        restInit, "RngSeed", i)

```

