---
title: "instance 1 (2013)"
output: html_document
---

### MSOpt  

```{r}
library(multiDoE)

options(digits = 10)

facts <- list(1, 2:5)
units <- list(6, 5)
levels <- 3
etas <- list(1)
criteria <- c('I', 'Id', 'D', 'A', 'Ds', 'As')
model <- "quadratic"

msopt <- MSOpt(facts, units, levels, etas, criteria, model)
msopt
```
 
### Score  

```{r}
example <- matrix(c( 0,  1,  0,  0,  0,
                     0,  0,  0,  1,  1,
                     0,  0, -1, -1,  0,
                     0,  0,  1,  0, -1,
                     0, -1,  0,  0,  0,
                     0,  0, -1,  0,  0,
                     0,  0,  1,  0,  0,
                     0, -1,  0,  0,  0,
                     0,  0,  0,  1, -1,
                     0,  1,  0, -1, -1,
                    -1, -1,  1, -1,  1,
                    -1,  1, -1, -1,  1,
                    -1, -1, -1,  1,  1,
                    -1,  1,  1,  1,  1,
                    -1,  0,  0,  0, -1,
                     1, -1, -1,  1, -1,
                     1,  0,  0, -1,  0,
                     1,  1,  1,  1, -1,
                     1, -1,  1,  1,  1,
                     1,  1, -1,  1,  1,
                    -1,  0,  0,  0,  1,
                    -1,  1, -1,  1, -1,
                    -1,  1,  1, -1,  0,
                    -1, -1, -1, -1, -1,
                    -1, -1,  1,  1, -1,
                     1,  1,  1, -1,  1,
                     1, -1,  1, -1, -1,
                     1,  1, -1,  0, -1,
                     1, -1, -1, -1,  1,
                     1,  0,  0,  1,  0),
                  ncol = 5, byrow = T)

score <- Score(msopt, example)

print(c(0.747685709700000, 0.543760607000000, 0.101656312400000, 0.182661344700000, 0.098274211800000, 0.104602040100000))
print(score)
```

### MSSearch (Single-criteria)

```{r}
library(multiDoE)
set.seed(1)
options(digits = 15)

facts <- list(1, 2:5)
units <- list(6, 5)
levels <- 3
etas <- list(1)
criteria <- c('I')
model <- "quadratic"

msopt1 <- MSOpt(facts, units, levels, etas, criteria, model)
mssearch1 <- MSSearch(msopt1, 1, "Restarts", 100, "Start", example,
                     "Normalize", c(0.1, 2))
mssearch1
# file_name <- here::here("tests/testthat/test_data/mssMsol_i1.Rds")
# saveRDS(mssearch1, file = file_name)
``` 

### MSSearch (Multi-criteria)  

```{r}
library(multiDoE)
set.seed(123)
options(digits = 10)

facts <- list(1, 2:5)
units <- list(6, 5)
levels <- 3
etas <- list(1)
criteria <- c('I', 'Id', 'D', 'A', 'Ds', 'As')
model <- "quadratic"

msopt <- MSOpt(facts, units, levels, etas, criteria, model)
mssearchM <- MSSearch(msopt, rep(1/6, 6), "Restarts", 100,
                      "Start", example)
mssearchM
#file_name <- here::here("tests/testthat/test_data/mssMsol_i1.Rds")
#saveRDS(mssearchM, file = file_name)
```

### TPLSearch  

```{r}
library(multiDoE)
set.seed(36)
options(digits = 10)

facts <- list(1, 2:5)
units <- list(6, 5)
levels <- 3
etas <- list(1)
# criteria <-  c('I', 'Id', 'D', 'A', 'Ds', 'As')
criteria <-  c('I', 'Id', 'D')
model <- "quadratic"

lCrit <- length(criteria)
iters <- 10 * lCrit
restarts <- 100
restInit <- 2
i = 70

tpls <- runTPLS(facts, units, criteria, model, iters, 
                "Etas", etas,
                "Levels", levels, 
                "Restarts", restarts, 
                "RestInit", restInit,
                "RngSeed", i)

```





### optMultiCrit  

```{r}
ParetoArch <- res$megaAR
optMultiCrit(ParetoArch)
```

### optSingleCrit  

```{r}
ParetoArch <- res$megaAR
colnames(res$megaAR$scores) <- criteria
sc <- optSingleCrit(ParetoArch)
sc
```



### plotPareto  

```{r}
ParetoArch <- res$megaAR
plotPareto(paretoArch)
```
